### ISSUE TITLE
Valeurs relevées incoherentes  

### ISSUE THREAD

**Issue by ALaDoffe** [tetienne/veolia-custom-component#22]
Hello

Tout d'abord merci pour votre intégration, cependant je rencontre des soucis avec les valeurs relevées dans HA.

![image](https://user-images.githubusercontent.com/62749332/127637743-58475564-b2a4-4ca5-bc69-80048ad764d2.png)

Des fois j'ai des valeurs "correctes"

De plus, j'ai dans les log HA 

```
Logger: homeassistant
Source: custom_components/veolia/sensor.py:34
Integration: Veolia (documentation, issues)
First occurred: July 28, 2021, 21:14:51 (29 occurrences)
Last logged: July 29, 2021, 23:40:12
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
    state = self._stringify_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 425, in _stringify_state
    state = self.state
  File "/home/homeassistant/.homeassistant/custom_components/veolia/sensor.py", line 34, in state
    return self.coordinator.data[HOURLY][hour - 1]
IndexError: list index out of range

```
J'ai bien activé dans mon interface Véolia la consommation horaire comme expliqué.

Avez vous une idée?

**Comment by tetienne** [comment]
Hello. Je vois deux souci ici :
- Le log qui indique un problème d'index 
- Et la valeur très élevée

Pour le premier point, c'est régulier ou bien est-ce arrivé qu'une fois ?
Pour le second point, je le rencontre aussi. Je vais essayer de comprendre dans la semaine ce qui se passe.

**Comment by ALaDoffe** [comment]
Hello,

Le problème d'index est récurent.

![image](https://user-images.githubusercontent.com/62749332/127746736-dfb7ad87-d987-4ad6-8515-c69c1fd63405.png)

La j'ai plus rien du tout.

![image](https://user-images.githubusercontent.com/62749332/127746590-fc3dae7e-41ff-46dd-8e24-8fd59f17b0b4.png)

Merci pour la prise en compte.
Si je peux aider, n’hésitez pas

**Comment by tetienne** [comment]
@ALaDoffe Pouvez-vous vous rendre sur https://www.eau-services.com/mon-espace-suivi-personnalise.aspx?mm=07/2021&d=28 et me partager le CSV disponible en cliquant sur *Télécharger les données* ?

![image](https://user-images.githubusercontent.com/8216238/127820375-70d8426b-7f91-4829-a7be-e494a9b449c4.png)

Cela me permettra de voir s’il y a quelque chose de non attendu dans le fichier retourné par Veolia.

**Comment by tetienne** [comment]
J’ai pu trouver cet exemple de relevé:

```CSV
date;consommation(litre)
01/03/2018;275
02/03/2018;154
03/03/2018;379
03/03/2018;-1754359
04/03/2018;1754558
```

De ce que je comprends, consommation du 4 est égale à celle indiquée moins l’avant dernière valeur: 1754558-1754359=199 ici

Je vais ajouter des log pour mieux comprendre.

**Comment by ALaDoffe** [comment]
@tetienne, ci dessous le fichier demandé et la capture d'ecran 

[export.csv](https://github.com/tetienne/veolia-custom-component/files/6918643/export.csv)


![image](https://user-images.githubusercontent.com/62749332/127901135-26afa8ed-3a60-4c8f-bd5a-fd292b2dd707.png)
 
Cordialement

**Comment by tetienne** [comment]
Quelqu’un de très sympatique chez Veolia m’a contacté. 
Les valeurs très négatives proviennent d’une erreur de transmission dû aux ondes, et pour corriger cette erreur une autre valeur très positive est transmise. Avec le revelé par heure, l’erreur est rapidement corrigé, et c’est pour cela que l’on ne voit plus le soucis dans le rapport que je vois en pièce jointe. Sans relevé horaire il faudrait attendre minuit.

Je vais donc voir pour ignorer les rapports contenant une telle valeur puisque Veolia corrige son erreur automatiquement.

**Comment by ALaDoffe** [comment]
Merci pour la prise en compte.
Pour confirmation, les données remontées sont toutes à J-3 ?

**Comment by tetienne** [comment]
Oui c'est bien ça. HA ne me permet pas encore de lier une donnée à une date passée.

**Comment by ALaDoffe** [comment]
Juste pour apporter des infos supplémentaires.
Les valeurs journalières et mensuelles sont mises à jour tous les soirs a 00:10 avec des indications fausses.
Si je reload l’intégration en journée les valeurs redeviennent bonnes, mais la consommation horaires est en erreur.

![image](https://user-images.githubusercontent.com/62749332/129372639-b19b6c64-fc00-4682-8ebc-4b899c64739a.png)

![image](https://user-images.githubusercontent.com/62749332/129372761-95e47873-06da-4751-9ea2-c235987a90e7.png)

**Comment by tetienne** [comment]
Le soucis devrait être corrigé sur la branche master. Une fois confirmé, je déploierai une version.

**Comment by ALaDoffe** [comment]
@tetienne 
Je viens de mettre a jour mon plugin sur la branche master.
Ça me semble ok pour le moment.

![image](https://user-images.githubusercontent.com/62749332/130752485-274365e4-19c7-4c57-85ac-3a82fea8f3aa.png)

Je ferai un update demain et/ou après demain pour confirmer.

Merci

**Comment by ALaDoffe** [comment]
Bonjour,

Désolé pour la réponse tardive.
En fait je n'ai pas pu vraiment vérifier car depuis le plugin ne marche plus du tout.
J'ai la même erreur que : https://github.com/tetienne/veolia-custom-component/issues/29

Pour info, cela a commencé fin aout si ça peut apporter de l'aide.

## Error
2021-09-26 09:54:43 ERROR (MainThread) [custom_components.veolia] Unexpected error fetching veolia consumption update data: 'consommation(litre)'
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/home/homeassistant/.homeassistant/custom_components/veolia/__init__.py", line 72, in _get_consumption
daily_consumption = await api.get_consumption(
File "/srv/homeassistant/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/srv/homeassistant/lib/python3.9/site-packages/pyolia/client.py", line 100, in get_consumption
return await self._get_daily_consumption(month, year)
File "/srv/homeassistant/lib/python3.9/site-packages/pyolia/client.py", line 109, in _get_daily_consumption
return [int(row[CONSUMPTION_HEADER]) for row in reader]
File "/srv/homeassistant/lib/python3.9/site-packages/pyolia/client.py", line 109, in <listcomp>
return [int(row[CONSUMPTION_HEADER]) for row in reader]
KeyError: 'consommation(litre)'
2021-09-26 09:54:43 WARNING (MainThread) [homeassistant.config_entries] Config entry 'XXXXXXX' for veolia integration not ready yet: None; Retrying in background
2021-09-26 09:54:57 ERROR (MainThread) [custom_components.veolia] Unexpected error fetching veolia consumption update data: 'consommation(litre)'
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/home/homeassistant/.homeassistant/custom_components/veolia/__init__.py", line 72, in _get_consumption
daily_consumption = await api.get_consumption(
File "/srv/homeassistant/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/srv/homeassistant/lib/python3.9/site-packages/pyolia/client.py", line 100, in get_consumption
return await self._get_daily_consumption(month, year)
File "/srv/homeassistant/lib/python3.9/site-packages/pyolia/client.py", line 109, in _get_daily_consumption
return [int(row[CONSUMPTION_HEADER]) for row in reader]
File "/srv/homeassistant/lib/python3.9/site-packages/pyolia/client.py", line 109, in <listcomp>
return [int(row[CONSUMPTION_HEADER]) for row in reader]
KeyError: 'consommation(litre)'

**Comment by tetienne** [comment]
le soucis de login est maintenant corrigé. Désolé d’avoir mis un si long moment à le corriger.
