### ISSUE TITLE
erreur 1ere connection : Réessayer la configuration: None

### ISSUE THREAD

**Issue by mathep34** [tetienne/veolia-custom-component#29]
Bonjour,
après 24h de fonctionnement, j'ai toujours le même message d'erreur "Réessayer la configuration: None"
et des messages dans la log voir ci-dessous.
Pourtant sur le site https://www.eau-services.com/ j'ai bien les données jours/heures. (site veolia méditerranée)

As-tu une idée ?
Merci

log ******************
2021-09-24 16:44:56 ERROR (MainThread) [custom_components.veolia] Unexpected error fetching veolia consumption update data: 'consommation(litre)'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/veolia/__init__.py", line 71, in _get_consumption
    daily_consumption = await api.get_consumption(
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyolia/client.py", line 100, in get_consumption
    return await self._get_daily_consumption(month, year)
  File "/usr/local/lib/python3.9/site-packages/pyolia/client.py", line 109, in _get_daily_consumption
    return [int(row[CONSUMPTION_HEADER]) for row in reader]
  File "/usr/local/lib/python3.9/site-packages/pyolia/client.py", line 109, in <listcomp>
    return [int(row[CONSUMPTION_HEADER]) for row in reader]
KeyError: 'consommation(litre)'

**Comment by tetienne** [comment]
Je rencontre en effet le même soucis. Je vais voir courant de la semaine prochaine d’où cela peut venir.

**Comment by tetienne** [comment]
Le soucis est maintenant corrigé avec la version 0.3.3.

**Comment by mathep34** [comment]
bonjour
tout fonctionne
merci a toi
pierre
